#!/bin/bash

# Define the trash directory
trash_dir="/trash"
mkdir -p "$trash_dir"

files_to_trash=()
use_real_rm=false

# Separate flags from files
for arg in "$@"; do
    case "$arg" in
        --help|--version) use_real_rm=true; break ;;
        -f|-i|-v|-I|--force|--interactive|--verbose) continue ;;
        -r|-R|--recursive) continue ;;
        -*) use_real_rm=true; break ;;
        *) files_to_trash+=("$arg") ;;
    esac
done

if [ "$use_real_rm" = true ] || [ ${#files_to_trash[@]} -eq 0 ]; then
    /bin/rm "$@"
else
    for file in "${files_to_trash[@]}"; do
        base_name=$(basename "$file")
        
        if [ -e "$trash_dir/$base_name" ]; then
            random_suffix=$(mktemp -u XXXXXXXXXXXX)
            mv "$file" "$trash_dir/${base_name}-${random_suffix}"
        else
            mv "$file" "$trash_dir/"
        fi
    done
fi
